
-- Génaration de la base de données Maesia (SGBD : MYSQL / LANGUAGE : SQL)
-- Blo 28/04/2020
-- Commentaires : 
--               
--               - Revoir le create de MOCHILD_GRADE


CREATE TABLE CONDITION_TYPE (
    COT_ID INTEGER PRIMARY KEY,
    COT_NAME VARCHAR(50),
    COT_DESCRIPTION VARCHAR(400)
);

CREATE TABLE MAE_CONDITION (
    CO_ID INTEGER PRIMARY KEY,
    COT_ID INTEGER
);

CREATE TABLE ITEM_TYPE (
    ITT_ID INTEGER PRIMARY KEY,
    ITT_NAME VARCHAR(50),
    ITT_LORE VARCHAR(200)
);

CREATE TABLE ITEM (
    IT_ID CHAR(6) PRIMARY KEY,
    IT_NAME VARCHAR(30),
    IT_LORE VARCHAR(200),
    IT_PALLIER INTEGER,
    ITT_ID INTEGER,
    CO_ID INTEGER,
    ITS_VIT INTEGER NULL,
    ITS_DEF INTEGER NULL,
    ITS_ENE INTEGER NULL,
    ITS_REG INTEGER NULL,
    ITS_CONC INTEGER NULL,
    ITS_VITE INTEGER NULL,
    ITS_PUI INTEGER NULL,
    ITS_CRI INTEGER NULL,
    ITS_ESQ INTEGER NULL,
    ITS_MEL INTEGER NULL,
    ITS_DIS INTEGER NULL,
    ITS_DEG INTEGER NULL,
    ITS_SOIN INTEGER NULL,
    ITS_PROV INTEGER NULL,
    ITS_CONT INTEGER NULL
);


CREATE TABLE ACTION_TYPE ( 
    ACT_ID INTEGER PRIMARY KEY,
    ACT_NAME VARCHAR(50)
);
CREATE TABLE ACTION ( 
    AC_ID INTEGER PRIMARY KEY,
    AC_NAME VARCHAR(50),
    ACT_ID INTEGER
);


CREATE TABLE QUEST (
    QU_ID INTEGER PRIMARY KEY,
    QU_NAME VARCHAR(50),
    QU_DESC VARCHAR(500),
    QU_REWARD_XP INTEGER,
    AC_ID INTEGER,
    CO_ID INTEGER
);


CREATE TABLE STEP (
    ST_ID INTEGER PRIMARY KEY,
    ST_NAME VARCHAR(30),
    ST_DESC VARCHAR(300),
    ST_POSITION INTEGER,
    QU_ID INTEGER
);


CREATE TABLE GOAL_TYPE (
    GO_ID INTEGER,
    GO_NAME VARCHAR(50),
    GO_AMOUNT INTEGER,
    PRIMARY KEY(GO_ID,GO_NAME)
);
CREATE TABLE GOAL (
    GO_ID INTEGER PRIMARY KEY,
    GO_NAME VARCHAR(30),
    ST_ID INTEGER,
    GOT_ID INTEGER
);


CREATE TABLE QUEST_ITEM_REWARD (
    QU_ID INTEGER,
    IT_ID CHAR(6),
    QR_AMOUNT INTEGER,
    PRIMARY KEY(QU_ID,IT_ID)
);




CREATE TABLE LOCATION ( 
    LO_ID INTEGER PRIMARY KEY,
    LO_NAME VARCHAR(50) NULL, 
    LO_X FLOAT,
    LO_Y FLOAT,
    LO_Z FLOAT,
    LO_PITCH FLOAT,
    LO_YAW FLOAT
);
CREATE TABLE REGION ( 
    RE_ID INTEGER PRIMARY KEY,
    RE_NAME VARCHAR(30),
    RE_DESC VARCHAR(300),
    LO_IDSPAWN INTEGER
);



CREATE TABLE ZONE ( 
    ZO_ID INTEGER PRIMARY KEY,
    ZO_NAME VARCHAR(30),
    ZO_DESC VARCHAR(300),
    LO_IDSPAWN INTEGER,
    RE_ID INTEGER
);
CREATE TABLE PORTAL (
    PO_ID INTEGER PRIMARY KEY,
    ZO_IDA INTEGER,
    LO_IDTPA INTEGER,
    ZO_IDB INTEGER,
    LO_IDTPB INTEGER
);
CREATE TABLE WG_REGION ( 
    WGR_ID INTEGER PRIMARY KEY,
    WGR_NAME VARCHAR(50),
    ZO_ID INTEGER
);


CREATE TABLE NPC ( 
    NPC_ID INTEGER PRIMARY KEY,
    LO_ID INTEGER,
    ZO_ID INTEGER,
    NPC_NAME VARCHAR(30)
);


CREATE TABLE SPAWN_TABLE (
    ST_ID INTEGER PRIMARY KEY,
    WGR_ID INTEGER,
    SPT_FREQUENCY DOUBLE, 
    SPT_MAXMOBS INTEGER
);


CREATE TABLE MOB (
    MO_ID INTEGER PRIMARY KEY,
    MO_NAME VARCHAR(30),
    MO_DESC VARCHAR(300),
    MO_BASEXP INTEGER
);
CREATE TABLE SPAWN_MOB (
    ST_ID INTEGER,
    MO_ID INTEGER,
    SPM_RARITY INTEGER,
    PRIMARY KEY(ST_ID,MO_ID)
);
CREATE TABLE LOOT_TABLE (
    IT_ID CHAR(6) PRIMARY KEY,
    IT_NAME VARCHAR(30)
);
CREATE TABLE LOOT_MOB (
    LT_ID CHAR(6),
    MO_ID INTEGER,
    PRIMARY KEY(LT_ID,MO_ID)
);
CREATE TABLE OPTION_TYPE (
    OP_ID INTEGER PRIMARY KEY,
    OP_NAME VARCHAR(40),
    OP_DESC VARCHAR(500)
);
CREATE TABLE GRADE (
    GR_ID INTEGER PRIMARY KEY,
    GR_NAME VARCHAR(20),
    GR_PREFIX VARCHAR(20),
    GR_RANK VARCHAR(20),
    GR_PERMISSION LONGTEXT
);
CREATE TABLE MOCHILD_GRADE ( 
    GR_IDCHILD INTEGER,
    GR_IDMOTHER INTEGER,
    PRIMARY KEY(GR_IDCHILD,GR_IDMOTHER)
);


CREATE TABLE PLAYER ( 
    PL_UUID CHAR(32) PRIMARY KEY,
    PL_PASSWORD VARCHAR(30),
    ZO_ID INTEGER,
    LO_ID INTEGER,
    GR_ID INTEGER
);
CREATE TABLE INV_TYPE (
    INVT_ID INTEGER PRIMARY KEY,
    INVT_NAME VARCHAR(50),
    INVT_CAPACITY INTEGER
);
CREATE TABLE INVENTORY (
    IN_ID INTEGER PRIMARY KEY,
    INVT_TYPE INTEGER,
    PL_UUID CHAR(32)
);
CREATE TABLE INV_SLOT (
    IN_ID INTEGER,
    IT_ID CHAR(6),
    INVS_SLOT INTEGER,
    INVS_AMOUNT INTEGER,
    INVS_QUALITY INTEGER,
    PRIMARY KEY(IN_ID,IT_ID)
);
CREATE TABLE LOOT_ITEM (
    LT_ID CHAR(6),
    IT_ID CHAR(6),
    LI_MAXAMOUNT INTEGER,
    LI_MINAMOUNT INTEGER,
    LI_CHANCE INTEGER,
    PRIMARY KEY(LT_ID,IT_ID)
);
CREATE TABLE PLAYER_OPTION (
    PL_UUID CHAR(32),
    OP_ID INTEGER,
    PRIMARY KEY(PL_UUID,OP_ID)
);
CREATE TABLE QUEST_STATE (
    PL_UUID CHAR(32),
    QU_ID INTEGER,
    QS_ISFINISH BOOLEAN,
    PRIMARY KEY(PL_UUID,QU_ID)
);

CREATE TABLE GOAL_STATE (
    PL_UUID CHAR(32),
    GO_ID INTEGER,
    GS_PROGRESS INTEGER,
    PRIMARY KEY(PL_UUID,GO_ID)
);

ALTER TABLE action ENGINE = InnoDB;
ALTER TABLE action_type ENGINE = InnoDB;
ALTER TABLE condition_type ENGINE = InnoDB;
ALTER TABLE goal ENGINE = InnoDB;
ALTER TABLE goal_state ENGINE = InnoDB;
ALTER TABLE goal_type ENGINE = InnoDB;
ALTER TABLE grade ENGINE = InnoDB;
ALTER TABLE inventory ENGINE = InnoDB;
ALTER TABLE inv_slot ENGINE = InnoDB;
ALTER TABLE inv_type ENGINE = InnoDB;
ALTER TABLE item ENGINE = InnoDB;
ALTER TABLE item_type ENGINE = InnoDB;
ALTER TABLE location ENGINE = InnoDB;
ALTER TABLE loot_item ENGINE = InnoDB;
ALTER TABLE loot_mob ENGINE = InnoDB;
ALTER TABLE loot_table ENGINE = InnoDB;
ALTER TABLE mae_condition ENGINE = InnoDB;
ALTER TABLE mob ENGINE = InnoDB;
ALTER TABLE mochild_grade ENGINE = InnoDB;
ALTER TABLE npc ENGINE = InnoDB;
ALTER TABLE option_type ENGINE = InnoDB;
ALTER TABLE player ENGINE = InnoDB;
ALTER TABLE player_option ENGINE = InnoDB;
ALTER TABLE portal ENGINE = InnoDB;
ALTER TABLE quest ENGINE = InnoDB;
ALTER TABLE quest_item_reward ENGINE = InnoDB;
ALTER TABLE quest_state ENGINE = InnoDB;
ALTER TABLE region ENGINE = InnoDB;
ALTER TABLE spawn_table ENGINE = InnoDB;
ALTER TABLE step ENGINE = InnoDB;
ALTER TABLE wg_region ENGINE = InnoDB;
ALTER TABLE zone ENGINE = InnoDB;

ALTER TABLE MAE_CONDITION
ADD FOREIGN KEY (COT_ID) REFERENCES CONDITION_TYPE(COT_ID); 
ALTER TABLE ITEM
ADD FOREIGN KEY (ITT_ID) REFERENCES ITEM_TYPE (ITT_ID);
ALTER TABLE ITEM
ADD FOREIGN KEY (CO_ID) REFERENCES MAE_CONDITION (CO_ID); 
ALTER TABLE ACTION
ADD FOREIGN KEY (ACT_ID) REFERENCES ACTION_TYPE (ACT_ID); 
ALTER TABLE QUEST
ADD FOREIGN KEY (AC_ID) REFERENCES ACTION (AC_ID);
ALTER TABLE QUEST
ADD FOREIGN KEY (CO_ID) REFERENCES MAE_CONDITION (CO_ID); 
ALTER TABLE STEP
ADD FOREIGN KEY (QU_ID) REFERENCES  QUEST (QU_ID);
ALTER TABLE GOAL
ADD FOREIGN KEY (ST_ID) REFERENCES STEP (ST_ID);
ALTER TABLE GOAL
ADD FOREIGN KEY (GOT_ID) REFERENCES GOAL_TYPE (GO_ID);
ALTER TABLE QUEST_ITEM_REWARD
ADD FOREIGN KEY (QU_ID) REFERENCES QUEST (QU_ID);
ALTER TABLE QUEST_ITEM_REWARD
ADD FOREIGN KEY (IT_ID) REFERENCES ITEM (IT_ID);
ALTER TABLE REGION
ADD FOREIGN KEY (LO_IDSPAWN) REFERENCES LOCATION (LO_ID);
ALTER TABLE ZONE
ADD FOREIGN KEY (LO_IDSPAWN) REFERENCES LOCATION (LO_ID);
ALTER TABLE ZONE
ADD FOREIGN KEY (RE_ID) REFERENCES REGION (RE_ID);
ALTER TABLE PORTAL
ADD FOREIGN KEY (ZO_IDA) REFERENCES ZONE (ZO_ID);
ALTER TABLE PORTAL
ADD FOREIGN KEY (LO_IDTPA) REFERENCES LOCATION (LO_ID);
ALTER TABLE PORTAL
ADD FOREIGN KEY (ZO_IDB) REFERENCES ZONE (ZO_ID);
ALTER TABLE PORTAL
ADD FOREIGN KEY (LO_IDTPB) REFERENCES LOCATION (LO_ID);
ALTER TABLE WG_REGION
ADD FOREIGN KEY (ZO_ID) REFERENCES ZONE (ZO_ID);
ALTER TABLE NPC
ADD FOREIGN KEY (LO_ID) REFERENCES LOCATION (LO_ID);
ALTER TABLE NPC
ADD FOREIGN KEY (ZO_ID) REFERENCES ZONE (ZO_ID);
ALTER TABLE SPAWN_TABLE
ADD FOREIGN KEY (WGR_ID) REFERENCES WG_REGION (WGR_ID);
ALTER TABLE SPAWN_MOB
ADD FOREIGN KEY (ST_ID) REFERENCES SPAWN_TABLE (ST_ID);
ALTER TABLE SPAWN_MOB
ADD FOREIGN KEY (MO_ID) REFERENCES MOB (MO_ID);
ALTER TABLE LOOT_MOB
ADD FOREIGN KEY (LT_ID) REFERENCES LOOT_TABLE (IT_ID);
ALTER TABLE LOOT_MOB
ADD FOREIGN KEY (MO_ID) REFERENCES MOB (MO_ID);
ALTER TABLE MOCHILD_GRADE
ADD FOREIGN KEY (GR_IDCHILD) REFERENCES GRADE (GR_ID);
ALTER TABLE MOCHILD_GRADE
ADD FOREIGN KEY (GR_IDMOTHER) REFERENCES  MOCHILD_GRADE (GR_IDCHILD);
ALTER TABLE PLAYER
ADD FOREIGN KEY (ZO_ID) REFERENCES ZONE (ZO_ID);
ALTER TABLE PLAYER
ADD FOREIGN KEY (LO_ID) REFERENCES LOCATION (LO_ID);
ALTER TABLE PLAYER
ADD FOREIGN KEY (GR_ID) REFERENCES GRADE (GR_ID);
ALTER TABLE INVENTORY
ADD FOREIGN KEY (INVT_TYPE) REFERENCES INV_TYPE (INVT_ID);
ALTER TABLE INVENTORY
ADD FOREIGN KEY (PL_UUID) REFERENCES PLAYER (PL_UUID);
ALTER TABLE INV_SLOT
ADD FOREIGN KEY (IN_ID) REFERENCES INVENTORY (IN_ID);
ALTER TABLE INV_SLOT
ADD FOREIGN KEY (IT_ID) REFERENCES ITEM (IT_ID);
ALTER TABLE LOOT_ITEM
ADD FOREIGN KEY (LT_ID) REFERENCES LOOT_TABLE (IT_ID);
ALTER TABLE LOOT_ITEM
ADD FOREIGN KEY (IT_ID) REFERENCES ITEM (IT_ID);
ALTER TABLE PLAYER_OPTION
ADD FOREIGN KEY (PL_UUID) REFERENCES PLAYER (PL_UUID);
ALTER TABLE PLAYER_OPTION
ADD FOREIGN KEY (OP_ID) REFERENCES OPTION_TYPE (OP_ID);
ALTER TABLE QUEST_STATE
ADD FOREIGN KEY (PL_UUID) REFERENCES PLAYER_OPTION (PL_UUID);
ALTER TABLE GOAL_STATE
ADD FOREIGN KEY (PL_UUID) REFERENCES PLAYER_OPTION (PL_UUID);
ALTER TABLE GOAL_STATE
ADD FOREIGN KEY (GO_ID) REFERENCES GOAL (GO_ID); 